config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => "homes#about"
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end

  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?
    def after_sign_in_path_for(resource)
      user_path(current_user.id)
    end

    def after_sign_in_path
      flash[:notice] = "Signed in successfully."
    end


    def after_sign_out_path_for(resource)
      root_path
    end

    def after_sign_out_path
      flash[:notice] = "Signed out successfully."
    end


    def after_sign_up_path_for(resource)
      user_path(current_user.id)
    end

    def after_sign_up_path
      flash[:notice] = "Welcome! You have signed up successfully."
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = book.id
    comment.save
    redirect_to book_path(params[:book_id])
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private
    def book_comment_params
      params.require(:book_comment).permit(:comment)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @new_book = Book.new
    @books = Book.all
    @current_user = User.find(current_user.id)
  end

  def create
    @books = Book.all
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      redirect_to book_path(@new_book.id)
      flash[:notice] = "You have created book successfully."
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @new_book_comment = BookComment.new
    @user = User.find(@book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render 'edit'
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] ="You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current_user = User.find(current_user.id)
    @new_book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render 'edit'
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<!-- ユーザープロフィール -->
<h2>User info</h2>

<%= image_tag user.get_profile_image(100,100) %>

<table class="table mb-5"><tbody>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>

  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</tbody></table>

<div class="row">
<a class="btn btn-outline-secondary btn-block" href="/users/<%= user.id %>/edit">
  <i class="fas fa-user-cog"></i>
</a>
</div>


<!-- 新規投稿 -->
<h2 class="mt-3">New book</h2>

<% if book.errors.any? %>
  <%= book.errors.count %> error(s)
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: book do |f| %>
  <div class="form-group">
    <label>Title</label><br>
    <input type="text" class="form-control" name="book[title]">
  </div>

  <div class="form-group">
    <label>Opinion</label><br>
    <textarea class="form-control" name="book[body]"></textarea>
  </div>

  <div class="form-group">
  <button class="btn btn-success btn-sm" type="submit">
    Create Book
  </button>
  </div>
<% end %>

app/views/books/edit.html.erb
<!-- 投稿編集 -->

<div class="container mt-3">
<div class="row">
<div class="col-5 mx-auto">

<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %> error(s)
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
  <div class="form-group">
    <label>Title</label><br>
    <input type="text" class="form-control" name="book[title]" value="<%= @book.title %>">
  </div>

  <div class="form-group">
    <label>Opinion</label><br>
    <textarea class="form-control" name="book[body]"><%= @book.body %></textarea>
  </div>

  <div class="form-group">
    <button class="btn btn-success" type="submit">
      Update Book
    </button>
  </div>
<% end %>

<%= link_to 'Show', book_path(@book) %>
<%= link_to 'Back', books_path %>

</div>
</div>
</div>

app/views/books/index.html.erb
<!-- 投稿一覧 -->

<div class="container mt-3">
<div class="row">

<div class="col-md-3">
  <%= render 'list', book: @new_book, user: @current_user %>
</div>

<div class="col-md-8 offset-md-1">
<h1>Books</h1>

<table class="table table-hover">
  <thead><tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th>Favorite</th>
    <th>Comment</th>
  </tr></thead>

  <tbody class="px-1">
  <% @books.each do |book| %>
  <tr>
    <td>
      <%= link_to user_path(book.user_id) do %>
        <%= image_tag book.user.get_profile_image(80,80) %>
      <% end %>
    </td>

    <td>
      <%= link_to book_path(book.id) do %>
        <%= book.title %>
      <% end %>
    </td>

    <td><%= book.body %></td>

    <td>
      <% if book.favorited_by?(current_user) %>
      <%= link_to book_favorites_path(book), method: :delete do %>
        <i class="fa-solid fa-heart"></i>&thinsp;<%= book.favorites.count %>
      <% end %>
    <% else %>
      <%= link_to book_favorites_path(book), method: :post do %>
        <i class="fa-solid fa-heart"></i>&thinsp;<%= book.favorites.count %>
      <% end %>
    <% end %>
    </td>

    <td><%= book.book_comments.count %>件</td>
  </tr>
  <% end %>
  </tbody>
</table>

</div>
</div>
</div>

app/views/books/show.html.erb
<!-- 投稿詳細 -->

<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<div class="container mt-3">
<div class="row">

<div class="col-md-3">
  <%= render 'list', book: @new_book, user: @user %>
</div>

<div class="col-md-8 offset-md-1">
<h2 class="pb-1">Book detail</h2>

<table class="table">
<tbody class="px-1">
  <tr class="align-top">
  <td class="col-2">
    <%= link_to user_path(@book.user_id) do %>
      <%= image_tag @book.user.get_profile_image(100,100) %><br>
      <%= @book.user.name %>
    <% end %>
  </td>

  <td class="col-2">
    <%= link_to book_path(@book.id) do %>
      <%= @book.title %>
    <% end %>
  </td>

  <td class="col-2"><%= @book.body %></td>

  <td class="col-2">
    <% if @book.favorited_by?(current_user) %>
      <%= link_to book_favorites_path(@book), method: :delete do %>
        <i class="fa-solid fa-heart"></i>&thinsp;<%= @book.favorites.count %>
      <% end %>
    <% else %>
      <%= link_to book_favorites_path(@book), method: :post do %>
        <i class="fa-solid fa-heart"></i>&thinsp;<%= @book.favorites.count %>
      <% end %>
    <% end %>
  </td>

  <td class="col-2"><%= @book.book_comments.count %>件のコメント</td>

  <% if @book.user == current_user %>
    <td class="col-1"><a class="btn btn-success btn-sm mb-2" href="/books/<%= @book.id %>/edit">Edit</a></td>
    <td class="col-1"><a class="btn btn-danger btn-sm mb-2" href="/books/<%= @book.id %>" data-method="delete" data-confirm="本当に消しますか？">Destroy</a></td>
  <% end %>
</tr>
</tbody>
</table>

<% @book.book_comments.each do |book_comment| %>
  <div class="ml-5 mb-2 d-flex">
    <%= link_to user_path(@book.user_id) do %>
      <%= image_tag book_comment.user.get_profile_image(100,100)%><br>
      <%= book_comment.user.name %>
    <% end %>

    <%= book_comment.comment %>

    <% if book_comment.user == current_user %>
      <a class="btn btn-danger btn-sm ml-3" href="/books/<%= @book.id %>/book_comments/<%= book_comment.id %>" data-method="delete">Destroy</a>
    <% end %>
  </div>
<% end %>

<%= form_with model: [@book, @new_book_comment] do |f| %>
  <div class="form-group mt-5">
    <label>Comment</label><br>
    <textarea class="form-control" name="book_comment[comment]"></textarea>
  </div>

  <div class="form-group">
  <button class="btn btn-secondary" type="submit">
    送信
  </button>
  </div>
<% end %>

</div>
</div>
</div>

app/views/homes/about.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
      <h1>
        Welcome to
        <i class="fas fa-book"></i><strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<div class="container mt-3">
  <div class="row">
    <div class="mx-auto col-11 col-xl-6">
      <h1>
        welcome to
        <i class="fas fa-book"></i><strong>Bookers</strong>
        !!
      </h1>

      <p>
        In

        <svg class="svg-inline--fa fa-book fa-w-14" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="book" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg="">
          <path fill="currentColor" d="M448 360V24c0-13.3-10.7-24-24-24H96C43 0 0 43 0 96v320c0 53 43 96 96 96h328c13.3 0 24-10.7 24-24v-16c0-7.5-3.5-14.3-8.9-18.7-4.2-15.4-4.2-59.3 0-74.7 5.4-4.3 8.9-11.1 8.9-18.6zM128 134c0-3.3 2.7-6 6-6h212c3.3 0 6 2.7 6 6v20c0 3.3-2.7 6-6 6H134c-3.3 0-6-2.7-6-6v-20zm0 64c0-3.3 2.7-6 6-6h212c3.3 0 6 2.7 6 6v20c0 3.3-2.7 6-6 6H134c-3.3 0-6-2.7-6-6v-20zm253.4 250H96c-17.7 0-32-14.3-32-32 0-17.6 14.4-32 32-32h285.4c-1.9 17.1-1.9 46.9 0 64z"></path>
        </svg><strong>Bookers</strong>,<br>
      </p>

      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-2" href="users/sign_in">Log in</a>
          <a class="btn btn-success btn-sm btn-block" href="users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>

          <% if user_signed_in? %><!-- ログインしている場合 -->
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <!-- ホーム -->
              <li><a class="nav-link text-light" href="/users/<%= current_user.id %>">
                <i class="fas fa-home"></i>
                Home
              </a></li>

              <!-- ユーザー一覧 -->
              <li><a class="nav-link text-light" href="/users">
                <i class="fas fa-users"></i>
                Users
              </a></li>

              <!-- 投稿一覧 -->
              <li><a class="nav-link text-light" href="/books">
                <i class="fas fa-book-open"></i>
                Books
              </a></li>

              <!-- ログアウト -->
              <li><a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
                <i class="fas fa-sign-out-alt"></i>
                Log out
              </a></li>

            </ul>
          </div>
          <% else %><!-- ログインしていない場合 -->
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <!-- ホーム -->
              <li><a class="nav-link text-light" href="/">
                <i class="fas fa-home"></i>
                Home
              </a></li>

              <!-- About -->
              <li><a class="nav-link text-light" href="/home/about">
                <i class="fas fa-link"></i>
                About
              </a></li>

              <!-- 新規登録 -->
              <li><a class="nav-link text-light" href="/users/sign_up">
                <i class="fas fa-user-plus"></i>
                Sign up
              </a></li>

              <!-- ログイン -->
              <li><a class="nav-link text-light" href="/users/sign_in">
                <i class="fas fa-sign-in-alt"></i>
                Log in
              </a></li>
            </ul>
            <% end %>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class"row">
          <div class="">
            <p class="text-center">CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<!-- ユーザー編集 -->

<div class="container mt-3">
<div class="row">
<div class="col-5 mx-auto">

<h2>User info</h2>

<% if @user.errors.any? %>
  <%= @user.errors.count %> error(s)
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @user do |f| %>
  <div class="form-group">
    <label>Name</label><br>
    <input type="text" class="form-control" name="user[name]" value="<%= @user.name %>">
  </div>

  <div class="form-group">
    <label>Image</label><br>
    <%= f.file_field :profile_image, accept: "image/*" %>
  </div>

  <div class="form-group">
    <label>Introduction</label><br>
    <textarea class="form-control" name="user[introduction]"><%= @user.introduction %></textarea>
  </div>

  <div class="form-group">
  <button class="btn btn-secondary" type="submit">
    Update User
  </button>
  </div>
<% end %>

</div>
</div>
</div>

app/views/users/index.html.erb
<!-- ユーザー一覧 -->

<div class="container mt-3">
<div class="row">

<div class="col-md-3">
  <%= render 'books/list', book: @new_book, user: @current_user %>
</div>

<div class="col-md-8 offset-md-1">
<h1>Users</h1>

<table class="table table-hover">
  <thead><tr>
    <th>image</th>
    <th>name</th>
    <th></th>
  </tr></thead>

  <tbody class="px=1">
  <% @users.each do |user| %>
  <tr>
    <td><%= image_tag user.get_profile_image(80,80) %></td>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user_path(user.id) %></td>
  </tr>
  <% end %>
  </tbody>
</table>

</div>

</div>
</div>

app/views/users/show.html.erb
<!-- ユーザー詳細 -->

<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<div class="container mt-3">
<div class="row">

<div class="col-md-3">
  <%= render 'books/list', book: @new_book, user: @user %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>

<table class="table table-hover">
  <thead><tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th>Favorite</th>
    <th>Comment</th>
  </tr></thead>

  <tbody class="px-1">
  <% @books.each do |book| %>
  <tr>
    <td>
      <%= link_to user_path(book.user_id) do %>
        <%= image_tag book.user.get_profile_image(80,80) %>
      <% end %>
    </td>

    <td>
      <%= link_to book_path(book.id) do %>
        <%= book.title %>
      <% end %>
    </td>

    <td><%= book.body %></td>

    <td>
      <% if book.favorited_by?(current_user) %>
      <%= link_to book_favorites_path(book), method: :delete do %>
        <i class="fa-solid fa-heart"></i>&thinsp;<%= book.favorites.count %>
      <% end %>
    <% else %>
      <%= link_to book_favorites_path(book), method: :post do %>
        <i class="fa-solid fa-heart"></i>&thinsp;<%= book.favorites.count %>
      <% end %>
    <% end %>
    </td>

    <td><%= book.book_comments.count %>件</td>
  </tr>
  <% end %>
  </tbody>
</table>
</div>

</div>
</div>